config/urls.py
"""
paeon URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
"""
main app URL Configuration
"""

from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
]

main/models.py
from statistics import mode
from django.db import models
from django.utils.translation import gettext as _

class PensionCompany(models.Model):
    name = models.TextField()  # 사업장명 / 회사명
    registration_number = models.TextField()  # 사업자등록번호
    lot_number_address = models.TextField()  # 지번주소
    road_name_address = models.TextField()  # 도로명주소
    employees_count = models.IntegerField()  # 기입자 수 / 사원 수
    data_created_at = models.CharField(
        max_length=7,
    )  # 자료 생성년월 (ex. '2022-02')
    
    class Meta:
        verbose_name = _('PensionCompany')
        verbose_name_plural = _('PensionCompanies')

main/views.py
from django.shortcuts import render
from .utils import get_similar_company_list_by_registration_from_pension_company, parse_registration_number

def index(request):
    registration_number = request.GET.get('registration_number')
    registration_name = request.GET.get('registration_name')
    keyword = request.GET.get('keyword')
    
    response = {
        'registration_number': registration_number or '',
        'registration_name': registration_name or '',
        'parsed_registration_number': parse_registration_number(registration_number or ''),
        'keyword': keyword or ''
    }
    
    if registration_number == None or registration_name == None:
        return render(request, 'index.html', response)
    
    response['company_list'] = get_similar_company_list_by_registration_from_pension_company(
        registration_name,
        registration_number,
        keyword
    )

    return render(request, 'index.html', response)

config/templates/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Paeon</title>

    {% block stylesheet %}
    {% endblock %}

  </head>
  <body>
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
  </body>
</html>

main/templates/_empty.dj.html
<tr>
  <td colspan="6">
    <strong class="text-center">
      검색결과가 없습니다. 사업자등록번호 또는 키워드가 올바른지 확인해주세요.
      <br />
      아래는 bizno.net의 검색 결과입니다. 
      
      <a href="https://bizno.net/article/{{parsed_registration_number}}" target="_blank" rel="noreferer noopener"> 링크 </a>
    </p>
    <iframe
      height="100%"
      width="80%"
      src="https://bizno.net/article/{{parsed_registration_number}}"
      style="min-height: 90vh"
    >
    </iframe>
  </td>
</tr>

main/templates/_form.dj.html
<form action="{% url 'main:index' %}" method="GET">
  <div class="tile is-ancestor p-3">
    <div class="tile is-child p-2 is-4">
      <div class="field">
        <label class="label">사업자 등록번호</label>
        <div class="control">
          <input
            class="input"
            name="registration_number"
            placeholder="000-00-00000"
            required="true"
            type="text"
            value="{{ registration_number }}"
          />
        </div>
        <p class="help">
          사업자 등록번호는 최소 6자리를 포함해서 넣어주세요. ('-'문자 유무 상관없음.)
        </p>
      </div>
    </div>
    <div class="tile is-child p-2 is-4">
      <div class="field">
        <label class="label">회사명</label>
        <div class="control">
          <input
            class="input"
            name="registration_name"
            placeholder="(주)그렙"
            required="true"
            type="text"
            value="{{ registration_name }}"
          />
        </div>
        <p class="help">
          회사명은 유사도 검색으로 찾을 회사명입니다.
        </p>
      </div>
    </div>


    <div class="tile is-child p-2 is-3">
      <div class="field">
        <label class="label">키워드</label>
        <div class="control">
          <input
            class="input"
            name="keyword"
            placeholder="그렙"
            type="text"
            value="{{ keyword }}"
          />
        </div>
        <p class="help">
          필수 키워드는 무조건 들어갈 것 같은 단어를 넣어 검색할 수 있습니다. 필수 X
        </p>
      </div>
    </div>

    <div class="tile is-child p-2 is-1" style="display: flex; align-items: center;">
      <button class="button is-link is-responsive" style="margin-top: 0.6rem">검색</button>
    </div>
  </div>
</form>

main/templates/_result_table.dj.html
<table class="table is-striped is-bordered is-fullwidth text-center">
  <thead>
    <tr>
      <th>복사하기</th>
      <th>상호명</th>

      <th>사업자등록번호</th>
      <th>지번 주소</th>
      <th>도로명 주소</th>
      <th>사원수</th>
      <th>생성일자</th>
    </tr>
  </thead>

  <tbody>
    {% for company in company_list %}
      <tr>
        {% for label, value in company %}
          {% if label == 'name' %}
            <th>
              <button onclick="copyToClipboard('{{ value }}')" class="btn">
                복사하기
              </button>
            </th>
          {% endif %}
          <td>{{ value }}</td>
        {% endfor %}
      </tr>
    {% empty %}
      {% if registration_number != '' and registration_name != '' %}
        {% include '_empty.dj.html' %}
      {% endif %}
    {% endfor %}
  </tbody>
</table>

main/templates/index.html
{% extends 'base.html' %}

{% block stylesheet %}
<style>
  .btn {
    color: black;
    cursor: pointer;
  }
  .text-center {
    text-align: center;
  }

  .menu {
    position: sticky;
    top: 0;
    background: white;
    margin-bottom: 1rem;
    border-bottom: 1px solid #D0DFDE;
  }
</style>
{% endblock %}

{% block content %}


<div class="m-2">
  <div class="menu">
    {% include '_form.dj.html' %}
  </div>
  {% include '_result_table.dj.html' %}
</div>

{% endblock %}


{% block script %}
<script>
  window.onbeforeunload = function () {
    window.scrollTo(0, 0);
  }

  function copyToClipboard(str) {
    const t = document.createElement("textarea");
    document.body.appendChild(t);
    t.value = str;
    t.select();
    document.execCommand("copy");
    document.body.removeChild(t);
  }
</script>
{% endblock %}